#!/bin/bash

echo hello world

osascript -e 'tell application "Terminal"' -e 'set mainID to id of front window' -e 'close (every window whose id ≠ mainID)' -e 'end tell'


# osascript -e 'tell application "System Events"
# 	tell application "Terminal" to activate
# 	keystroke "c" using {control down}
# end tell'

# killall python

# osascript -e 'tell application "Terminal" 
# set mainID to id of front window 
# set wis to every window whose id ≠ mainID
#     repeat with w in wis
#         tell application "System Events" to keystroke "c"  using {control down}
#     end repeat
# end tell'

# osascript -e 'tell application "Terminal" 
# set mainID to id of front window 
# tell (every window whose id ≠ mainID) 
#             tell its sheet 1
#                 click button "Close"
#             end tell
#         end tell'

# killall Terminal

# die="my-service"

# case $(pgrep -cf "$die") in
#     0) exit 0 ;;
#     1) pkill -f "$die" ;;
#     *) grep -v $(pgrep -nf "$die") <(pgrep -f "$die") | xargs kill ;;
# esac

# killall python
# osascript -e 'tell application "Terminal"' -e 'set mainID to id of front window' -e 'close (every window whose id ≠ mainID)' -e 'end tell'

# trap "echo hello" SIGINT



make all

pwd=`pwd`
serverC="$pwd/serverC"
serverP="$pwd/serverP"
serverS="$pwd/serverS"
serverT="$pwd/serverT"
clientA="$pwd/clientA"
clientB="$pwd/clientB"


osascript -e "tell application \"Terminal\" to do script \"$serverC\""
osascript -e "tell application \"Terminal\" to do script \"$serverP\""
osascript -e "tell application \"Terminal\" to do script \"$serverS\""
osascript -e "tell application \"Terminal\" to do script \"$serverT\""
osascript -e "tell application \"Terminal\" to do script \"$clientA Victor\""
osascript -e "tell application \"Terminal\" to do script \"$clientB Oliver\""


