# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'yelpReviewApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for yelpReviewApp

#  pod 'Kingfisher'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Kingfisher/SwiftUI'

  target 'yelpReviewAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'yelpReviewAppUITests' do
    # Pods for testing
  end

end
